import { Shield, BookOpen, AlertTriangle } from 'lucide-react';

export const AboutPage: React.FC = () => {
  const threatModel = [
    {
      threat: 'Malicious File Uploads / Polyglots',
      impact: 'Remote code execution or parser memory exhaustion.',
      mitigation: 'Strict magic byte validation (PNG signature / BMP BM), Pillow safe verification with image.load(), and rejection of non-image streams.',
      residual: 'Low. Zero native binary execution or system shell spawning.',
    },
    {
      threat: 'Path Traversal Attacks',
      impact: 'Arbitrary filesystem read/write or overwriting system files.',
      mitigation: 'Strict sanitization of user-provided filenames using regex [^a-zA-Z0-9_.-], stripping path separators, and writing to managed temp directories.',
      residual: 'Very Low. Paths resolved strictly inside isolated storage/temp.',
    },
    {
      threat: 'Resource Exhaustion (DoS / Decompression Bombs)',
      impact: 'Server memory starvation or crash via oversized decompression.',
      mitigation: '20MB hard file-size ceiling enforced before parsing, PIL pixel limit checks.',
      residual: 'Low. Capped memory buffers and streaming hash calculation.',
    },
    {
      threat: 'Payload Tampering & Bit Flipping',
      impact: 'Malleability of decrypted plaintext without knowing password.',
      mitigation: 'AES-256-GCM authenticated encryption with 128-bit authentication tag and payload SHA-256 integrity checksum.',
      residual: 'Negligible. Authenticated tags are mathematically unforgeable.',
    },
    {
      threat: 'Password Guessing / Brute Force',
      impact: 'Unauthorized recovery of secret embedded messages.',
      mitigation: 'PBKDF2-HMAC-SHA256 with 600,000 iterations creates significant computational friction (0.5s+ per attempt).',
      residual: 'Low. Dependent on user choosing sufficient entropy password.',
    },
    {
      threat: 'Information & Stack Trace Leakage',
      impact: 'Exposing backend internal directory structures or libraries.',
      mitigation: 'FastAPI custom exception handlers map domain exceptions to sanitized JSON error responses. Debug stack traces suppressed.',
      residual: 'Negligible. Logs are kept in server stdout; API returns clean errors.',
    },
  ];

  return (
    <div className="space-y-8 max-w-5xl mx-auto pb-16">
      <div className="border-b border-slate-800 pb-4">
        <h2 className="text-2xl font-black text-white tracking-tight">
          About StegoVault: Educational Cybersecurity Architecture
        </h2>
        <p className="text-xs text-slate-400 mt-1">
          Designed as a serious educational platform for digital forensics, cryptography, and steganography researchers.
        </p>
      </div>

      {/* Educational Theory Section */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 backdrop-blur space-y-4">
        <h3 className="text-base font-bold text-white flex items-center gap-2">
          <BookOpen className="h-5 w-5 text-cyan-400" />
          <span>Core Digital Forensics & Steganalysis Principles</span>
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs leading-relaxed text-slate-300 pt-2">
          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-1.5">
            <h4 className="font-bold text-cyan-300">1. LSB Steganography</h4>
            <p className="text-slate-400">
              Least Significant Bit (LSB) embedding substitutes the lowest bit of an 8-bit color channel (values 0–255). Changing the LSB modifies pixel intensity by at most ±1 unit, which is imperceptible to the human eye under normal lighting conditions.
            </p>
          </div>

          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-1.5">
            <h4 className="font-bold text-cyan-300">2. Why Encryption is Essential</h4>
            <p className="text-slate-400">
              Unencrypted plaintext ASCII characters have distinct bit patterns (e.g. ASCII characters begin with 01...). Encrypted ciphertext generated by modern ciphers (AES-256-GCM) is statistically indistinguishable from uniform white noise, evading string search and frequency analysis.
            </p>
          </div>

          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-1.5">
            <h4 className="font-bold text-cyan-300">3. Shannon Entropy</h4>
            <p className="text-slate-400">
              Information entropy quantifies unpredictability. In 8-bit channels, theoretical maximum entropy is 8.0 bits/symbol. In natural photography, LSB entropy typically ranges between 0.70 and 0.95. High-density encrypted payloads drive LSB entropy to approximately 1.000.
            </p>
          </div>

          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-1.5">
            <h4 className="font-bold text-cyan-300">4. False Positives & Negatives</h4>
            <p className="text-slate-400">
              A <strong>False Positive</strong> occurs when high sensor noise, camera ISO artifacts, or dithering trigger stego indicators in a clean image. A <strong>False Negative</strong> occurs when tiny payloads occupy a minuscule fraction of image capacity, evading macro statistical detection.
            </p>
          </div>
        </div>
      </div>

      {/* Threat Model Matrix */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 backdrop-blur space-y-4">
        <h3 className="text-base font-bold text-white flex items-center gap-2">
          <Shield className="h-5 w-5 text-emerald-400" />
          <span>StegoVault Threat Model Matrix</span>
        </h3>
        <p className="text-xs text-slate-400">
          Formal threat modeling evaluating adversary capabilities, system impacts, mitigations, and residual risk.
        </p>

        <div className="mt-4 overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400">
                <th className="pb-2.5 font-semibold uppercase">Threat</th>
                <th className="pb-2.5 font-semibold uppercase">Potential Impact</th>
                <th className="pb-2.5 font-semibold uppercase">Engineering Mitigation</th>
                <th className="pb-2.5 font-semibold uppercase">Residual Risk</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-slate-300">
              {threatModel.map((item, i) => (
                <tr key={i} className="hover:bg-slate-800/20 transition-colors">
                  <td className="py-3 font-semibold text-slate-100 pr-3">{item.threat}</td>
                  <td className="py-3 text-rose-300 pr-3">{item.impact}</td>
                  <td className="py-3 text-slate-300 pr-3">{item.mitigation}</td>
                  <td className="py-3 font-mono text-emerald-400 font-bold">{item.residual}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Limitations Disclaimer */}
      <div className="rounded-2xl border border-amber-500/30 bg-amber-950/20 p-6 backdrop-blur space-y-2">
        <div className="flex items-center gap-2 text-amber-400 font-bold text-sm">
          <AlertTriangle className="h-5 w-5" />
          <span>Platform Scope & Scientific Limitations</span>
        </div>
        <p className="text-xs leading-relaxed text-amber-200/90">
          <strong>Absence of detected indicators does not prove that an image contains no hidden data.</strong> Advanced adaptive steganography algorithms (such as WOW, UNIWARD, or HUGO) embed data selectively into high-texture complex regions rather than sequential LSB lines, which can successfully bypass first-order statistical and Chi-Square detectors. StegoVault provides defensive educational indicators, not absolute mathematical proof of absence.
        </p>
      </div>
    </div>
  );
};
